theme: jekyll-theme-primer
title: MSA Crime Prediction
description: Attempt to predict future crimes within an MSA
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
